### ISSUE TITLE
eCraft2Learn Troubleshooting Styling

### ISSUE THREAD

**Issue by afsheenam** [ecraft2learn/uui#16]
This is what I see on the troubleshooting page

![image](https://user-images.githubusercontent.com/35801506/37715907-e0afed18-2d25-11e8-87d3-632cd7b76027.png)

The css styling is not kicking in?

**Comment by afsheenam** [comment]
This is fixed now. Please note that you might need to "Clear" your "Browsing Data" to see it.

To delete cookies and cache for a specific site in Google Chrome, follow the instructions given below:

Launch Google Chrome and click on the Menu on the top right corner and click on Settings.
Scroll to the bottom and click on “Show advanced settings”.
Under Privacy section, click on Content Settings.
Under Cookies, click on All cookies and site data. It opens a new window with a list showing all stored cookies and cache.
Type the name of the website (for which you want to delete data, ex. Google.com) in the “Search cookies” text box in the top right corner. The list is filtered showing only data from the searched domain.
Now delete individual site data by clicking on the cross at the right side, or clear everything in the filtered list by clicking on the Remove all button. Thus, you can remove cookies and data for specific sites on Chrome.

You must do this for ecraft2learn.github.io

**Comment by afsheenam** [comment]
Please let me know if this works, after that I will close the issue.

**Comment by Calkin-eC2L** [comment]
this information should also be included in the troubleshooting pages of the UUI. Something like 'Styling issues', for instance

**Comment by Calkin-eC2L** [comment]
I am trying to follow your instructions but where is the Menu in the top right corner?

![image](https://user-images.githubusercontent.com/35801506/37760444-621ed32a-2dbf-11e8-8dc0-784464ca6ff6.png)

**Comment by afsheenam** [comment]
The menu button for Chrome, not the UUI. See below:
![image](https://user-images.githubusercontent.com/31007804/37776384-732421ae-2de5-11e8-857d-e5cad55bd2bd.png)

**Comment by afsheenam** [comment]
_"this information should also be included in the troubleshooting pages of the UUI. Something like 'Styling issues', for instance"_

I will add that.

**Comment by ToonTalk** [comment]
The information for styling issues is inappropriate.

Ctrl+F5 or Shift+F5 will re-download cached css and other files. (Or holding down control and clicking the refresh icon.)

Also I don't believe the troubleshooting page should have this styling section at all, since it only applies to users of the UUI that used it before 21 March and then used it again a short time later (cached files don't last that long). I believe this problem should never occur again so why clutter up the troubleshooting page?

Also the troubleshooting page now contains an image that is too wide causing horizontal scrolling:

![image](https://user-images.githubusercontent.com/2138696/37949047-925abed8-31b0-11e8-920e-a81d9beb457b.png)

**Comment by afsheenam** [comment]
Source for the information: https://support.google.com/chrome/answer/157179?visit_id=1-636578423501440813-2821879772&hl=en&rd=2

I agree that this information is not much needed, as the circumstances that anyone else will have the same problem are very low. In any case I think it is better to keep it.

I can fix the issue with the image.

**Comment by ToonTalk** [comment]
Following the Chrome link I see 

Reload the current page, ignoring cached content | Shift + F5 or Ctrl + Shift + r

I assume it also works for embedded iframes but perhaps not.
