### ISSUE TITLE
eCraft Search tool suggestion

### ISSUE THREAD

**Issue by ToonTalk** [ecraft2learn/uui#2]
I tried to type a query to the opening page where it says "Search for ideas" and typing did nothing. If all one can do on the page is click the 'Search' button why not jump right to that search page?

**Comment by Calkin-eC2L** [comment]
The teachers found it very confusing to have a 'search for ideas' text in there that when clicked does nothing. Delete this text or better yet make the entire text a search button (instead of only the small 'search' word as a button. See image below).

![image](https://user-images.githubusercontent.com/35801506/37649545-cc392688-2c3a-11e8-8f13-957d8fb05b88.png)

@tapanit-e

**Comment by Calkin-eC2L** [comment]
**Further comments when using the tool in mobile devices**
1. the 'x' (close) button is not working properly - it has erratic behaviour and becomes irresponsive 
2. Scrolling down is not working on the search results through a mobile device _**(this is true for all other windows that are opened in the UUI through a mobile device)**_

@tapanit-e 
@afsheenam

**Comment by phlindstedt** [comment]
I believe all this is fixed now. Now there's a search box directly to type and search with. Also the scrolling for mobile is working (Should be working for all created windows)
