### ISSUE TITLE
UUI - S4A connectivity issue

### ISSUE THREAD

**Issue by Calkin-eC2L** [ecraft2learn/uui#3]
I am trying to use the S4A environment within the UUI but the following error shows (see image below).
There is nothing in the troubleshooting link about how to solve this issue.

Assistance needed.

![image](https://user-images.githubusercontent.com/35801506/35562935-b70f763e-05bd-11e8-97bd-dc7a8c402703.png)

**Comment by ToonTalk** [comment]
I've been using snap4arduino.rocks for over a year and I also get this 1 or 2% of the time. The solution is that we host a copy of Snap4Arduino on github.io (since it is more reliable and the UUI depends on the same server). But there remains an issue regarding how to get around a security block in the Chrome extension. 3 possible solutions listed here: https://github.com/bromagosa/Snap4Arduino/issues/225

**Comment by Calkin-eC2L** [comment]
this is something that we need to carefully explain in the troubleshooting instructions. There end users (teachers +  students) will not go to deep into finding out solutions for the UUI to work properly - the time for each session/lesson is very limited at school.
Will have a local copy of S4A in the repository work?  will there still be security issues?
This is very serious

**Comment by ToonTalk** [comment]
The security issue is that the Snap4Arduino extension has access to the serial port (USB devices). The Snap4Arduino developers don't want their extension to be misused. But of course in our context the use is to communicate with an Arduino so all is well. We just need to either get them to add ecrat2learn.io to their list of trusted sites or we need to create our own copy of the Chrome extension.

**Comment by Calkin-eC2L** [comment]
this issue is still there. Any progress on this front? @ToonTalk

**Comment by ToonTalk** [comment]
Yes!!

OK I made a copy of Snap4Arduino at https://ecraft2learn.github.io/uui/snap4arduino (note it is HTTPS it can access microphone, camera, and AI cloud services)

The released CRX extension won't accept this but this folder https://ecraft2learn.github.io/uui/snap4arduino/crx.zip works just as well.

Those who are generating Raspberry PI SD Cards (and everyone who isn't using an eCraft SD card) needs to unzip crx.zip, go to chrome://extensions and drag and drop the folder there. Only difference from before is you drop the CRX folder instead of the CRX file.

I've updated the UUI to use our copy of Snap4Arduino and added some documentation about the need to use this folder instead of the CRX file.

Tested on my laptop and my Raspberry Pi.
