### ISSUE TITLE
Image missing for ArduinoBot help page

### ISSUE THREAD

**Issue by ToonTalk** [ecraft2learn/uui#33]
https://ecraft2learn.github.io/images/arduinobot.png

doesn't exist and reference from the help page.

**Comment by mazekeeper** [comment]
https://ecraft2learn.github.io/uui/about/arduinobot-help.html seems to have it. 
It should be https://ecraft2learn.github.io/uui/images/arduinobot.png  and not
https://ecraft2learn.github.io/images/arduinobot.png
(perhaps it's fixed already?)

**Comment by phlindstedt** [comment]
Now it's fixed. the (?) on the app work now and the popup will show correct image. 
When going directly to https://ecraft2learn.github.io/uui/about/arduinobot-help.html it will not work anymore and shouldn't since the popup will load the file content and then append it rather then use it as a iframe
